FAILED. Ran 39 tests in 0.794s (errors=0, failures=2, skipped=0)
/home/user/Projects/myapp/lib/tests/test_api.py:249: test_api : AssertionError: 'Illegal Blah transition [draft]->[invalid_status]' not found in '2019-08-20 18\:53\:43\: Created [draft]' : self.assertIn('Illegal Blah transition [draft]->[invalid_status]', model.history.splitlines()[-1])
/home/user/Projects/myapp/lib/tests/test_api.py:478: test_something_else : AssertionError: SomethingError not raised : self.assertIsNone(fut1.result())
