FAILED. Ran 28 tests in 38.686s (errors=2, failures=0, skipped=0)
/home/user/Projects/myapp/tests/conftest.py:164:12: inherited_image : subprocess.CalledProcessError: Command '['docker', 'build', '-f', PosixPath('/tmp/pytest-of-user/pytest-155/inherited0/Dockerfile'), '--tag', 'localhost:32000/test-firmus/python:3.9-inherited', '.']' returned non-zero exit status 1. : return inherited_docker_build("--tag", inherited_repo_tag)
/home/user/Projects/myapp/tests/conftest.py:156:`-  _inherited_docker_build :  : proc.check_returncode()
/home/user/Projects/myapp/tests/conftest.py:164:12: inherited_image : subprocess.CalledProcessError: Command '['docker', 'build', '-f', PosixPath('/tmp/pytest-of-user/pytest-155/inherited2/Dockerfile'), '--tag', 'localhost:32000/test-firmus/python:3.10-inherited', '.']' returned non-zero exit status 1. : return inherited_docker_build("--tag", inherited_repo_tag)
/home/user/Projects/myapp/tests/conftest.py:156:`-  _inherited_docker_build :  : proc.check_returncode()
